CREATE SCHEMA IF NOT EXISTS bl_dm;


CREATE TABLE IF NOT EXISTS bl_dm.dim_deliveries (
  delivery_id                BIGINT PRIMARY KEY DEFAULT -1,
  delivery_status_id         BIGINT      NOT NULL DEFAULT -1,
  delivery_status_name       VARCHAR     NOT NULL DEFAULT 'UNKNOWN',
  delivery_type_id           BIGINT      NOT NULL DEFAULT -1,
  delivery_type_name         VARCHAR     NOT NULL DEFAULT 'UNKNOWN',
  delivery_dt                DATE        NOT NULL DEFAULT DATE '1900-01-01',
  courier_company_id         BIGINT      NOT NULL DEFAULT -1,
  courier_company_name       VARCHAR     NOT NULL DEFAULT 'UNKNOWN',
  delivery_address_id        BIGINT      NOT NULL DEFAULT -1,
  courier_id                 BIGINT      NOT NULL DEFAULT -1,
  street                     VARCHAR     NOT NULL DEFAULT 'UNKNOWN',
  house_number               VARCHAR     NOT NULL DEFAULT 'UNKNOWN',
  apartment_number           VARCHAR     NOT NULL DEFAULT 'UNKNOWN',
  postal_code                VARCHAR     NOT NULL DEFAULT 'UNKNOWN',
  city_id                    BIGINT      NOT NULL DEFAULT -1,
  city_name                  VARCHAR     NOT NULL DEFAULT 'UNKNOWN',
  region_id                  BIGINT      NOT NULL DEFAULT -1,
  region_name                VARCHAR     NOT NULL DEFAULT 'UNKNOWN',
  country_id                 BIGINT      NOT NULL DEFAULT -1,
  country_code               VARCHAR     NOT NULL DEFAULT 'UNKNOWN',
  country_name               VARCHAR     NOT NULL DEFAULT 'UNKNOWN',
  ta_insert_dt               DATE        NOT NULL DEFAULT CURRENT_DATE,
  ta_update_dt               DATE        NOT NULL DEFAULT CURRENT_DATE,
  source_system              VARCHAR     NOT NULL DEFAULT 'UNKNOWN',
  source_entity              VARCHAR     NOT NULL DEFAULT 'UNKNOWN',
  source_delivery_id         VARCHAR     NOT NULL DEFAULT 'UNKNOWN'
);

CREATE TABLE IF NOT EXISTS bl_dm.dim_warehouses (
  warehouse_id               BIGINT PRIMARY KEY DEFAULT -1,
  warehouse_type_id          BIGINT      NOT NULL DEFAULT -1,
  warehouse_type_name        VARCHAR     NOT NULL DEFAULT 'UNKNOWN',
  num_employees              BIGINT      NOT NULL DEFAULT -1,
  capacity_units             BIGINT      NOT NULL DEFAULT -1,
  address_id                 BIGINT      NOT NULL DEFAULT -1,
  street                     VARCHAR     NOT NULL DEFAULT 'UNKNOWN',
  house_number               VARCHAR     NOT NULL DEFAULT 'UNKNOWN',
  apartment_number           VARCHAR     NOT NULL DEFAULT 'UNKNOWN',
  postal_code                VARCHAR     NOT NULL DEFAULT 'UNKNOWN',
  city_id                    BIGINT      NOT NULL DEFAULT -1,
  city_name                  VARCHAR     NOT NULL DEFAULT 'UNKNOWN',
  region_id                  BIGINT      NOT NULL DEFAULT -1,
  region_name                VARCHAR     NOT NULL DEFAULT 'UNKNOWN',
  country_id                 BIGINT      NOT NULL DEFAULT -1,
  country_code               VARCHAR     NOT NULL DEFAULT 'UNKNOWN',
  country_name               VARCHAR     NOT NULL DEFAULT 'UNKNOWN',
  ta_insert_dt               DATE        NOT NULL DEFAULT CURRENT_DATE,
  ta_update_dt               DATE        NOT NULL DEFAULT CURRENT_DATE,
  source_system              VARCHAR     NOT NULL DEFAULT 'UNKNOWN',
  source_entity              VARCHAR     NOT NULL DEFAULT 'UNKNOWN',
  source_warehouse_id        BIGINT      NOT NULL DEFAULT -1
);

CREATE TABLE IF NOT EXISTS bl_dm.dim_cashiers (
  cashier_id                 BIGINT PRIMARY KEY DEFAULT -1,
  first_name                 VARCHAR     NOT NULL DEFAULT 'UNKNOWN',
  last_name                  VARCHAR     NOT NULL DEFAULT 'UNKNOWN',
  email                      VARCHAR     NOT NULL DEFAULT 'UNKNOWN',
  phone                      VARCHAR     NOT NULL DEFAULT 'UNKNOWN',
  employment_dt              DATE        NOT NULL DEFAULT DATE '1900-01-01',
  role_id                    BIGINT      NOT NULL DEFAULT -1,
  role_name                  VARCHAR     NOT NULL DEFAULT 'UNKNOWN',
  shift_id                   BIGINT      NOT NULL DEFAULT -1,
  shift_name                 VARCHAR     NOT NULL DEFAULT 'UNKNOWN',
  cashier_address_id         BIGINT      NOT NULL DEFAULT -1,
  street                     VARCHAR     NOT NULL DEFAULT 'UNKNOWN',
  house_number               VARCHAR     NOT NULL DEFAULT 'UNKNOWN',
  apartment_number           VARCHAR     NOT NULL DEFAULT 'UNKNOWN',
  postal_code                VARCHAR     NOT NULL DEFAULT 'UNKNOWN',
  city_id                    BIGINT      NOT NULL DEFAULT -1,
  city_name                  VARCHAR     NOT NULL DEFAULT 'UNKNOWN',
  region_id                  BIGINT      NOT NULL DEFAULT -1,
  region_name                VARCHAR     NOT NULL DEFAULT 'UNKNOWN',
  country_id                 BIGINT      NOT NULL DEFAULT -1,
  country_code               VARCHAR     NOT NULL DEFAULT 'UNKNOWN',
  country_name               VARCHAR     NOT NULL DEFAULT 'UNKNOWN',
  ta_insert_dt               DATE        NOT NULL DEFAULT CURRENT_DATE,
  ta_update_dt               DATE        NOT NULL DEFAULT CURRENT_DATE,
  source_system              VARCHAR     NOT NULL DEFAULT 'UNKNOWN',
  source_entity              VARCHAR     NOT NULL DEFAULT 'UNKNOWN',
  source_customer_id         BIGINT      NOT NULL DEFAULT -1
);

CREATE TABLE IF NOT EXISTS bl_dm.dim_customers (
  customer_id                           BIGINT PRIMARY KEY DEFAULT -1,
  first_name                            VARCHAR     NOT NULL DEFAULT 'UNKNOWN',
  last_name                             VARCHAR     NOT NULL DEFAULT 'UNKNOWN',
  email                                 VARCHAR     NOT NULL DEFAULT 'UNKNOWN',
  phone                                 VARCHAR     NOT NULL DEFAULT 'UNKNOWN',
  registration_dt                        DATE        NOT NULL DEFAULT DATE '1900-01-01',
  preferred_communication_channel_id      BIGINT      NOT NULL DEFAULT -1,
  preferred_communication_channel_name    VARCHAR     NOT NULL DEFAULT 'UNKNOWN',
  loyalty_card_number                    VARCHAR     NOT NULL DEFAULT 'UNKNOWN',
  customer_address_id                    BIGINT      NOT NULL DEFAULT -1,
  street                                VARCHAR     NOT NULL DEFAULT 'UNKNOWN',
  house_number                          VARCHAR     NOT NULL DEFAULT 'UNKNOWN',
  apartment_number                      VARCHAR     NOT NULL DEFAULT 'UNKNOWN',
  postal_code                           VARCHAR     NOT NULL DEFAULT 'UNKNOWN',
  city_id                               BIGINT      NOT NULL DEFAULT -1,
  city_name                             VARCHAR     NOT NULL DEFAULT 'UNKNOWN',
  region_id                             BIGINT      NOT NULL DEFAULT -1,
  region_name                           VARCHAR     NOT NULL DEFAULT 'UNKNOWN',
  country_id                            BIGINT      NOT NULL DEFAULT -1,
  country_code                          VARCHAR     NOT NULL DEFAULT 'UNKNOWN',
  country_name                          VARCHAR     NOT NULL DEFAULT 'UNKNOWN',
  ta_insert_dt                           DATE        NOT NULL DEFAULT CURRENT_DATE,
  ta_update_dt                           DATE        NOT NULL DEFAULT CURRENT_DATE,
  source_system                          VARCHAR     NOT NULL DEFAULT 'UNKNOWN',
  source_entity                          VARCHAR     NOT NULL DEFAULT 'UNKNOWN',
  source_customer_id                     BIGINT      NOT NULL DEFAULT -1
);

CREATE TABLE IF NOT EXISTS bl_dm.dim_order_status (
  order_status_id            BIGINT PRIMARY KEY DEFAULT -1,
  order_status_name          VARCHAR     NOT NULL DEFAULT 'UNKNOWN',
  ta_insert_dt               DATE        NOT NULL DEFAULT CURRENT_DATE,
  source_system              VARCHAR     NOT NULL DEFAULT 'UNKNOWN',
  source_entity              VARCHAR     NOT NULL DEFAULT 'UNKNOWN',
  source_order_status_id     VARCHAR     NOT NULL DEFAULT 'UNKNOWN'
);

CREATE TABLE IF NOT EXISTS bl_dm.dim_stores (
  store_id                   BIGINT PRIMARY KEY DEFAULT -1,
  store_name                 VARCHAR     NOT NULL DEFAULT 'UNKNOWN',
  store_format_id            BIGINT      NOT NULL DEFAULT -1,
  store_format_name          VARCHAR     NOT NULL DEFAULT 'UNKNOWN',
  store_address_id           BIGINT      NOT NULL DEFAULT -1,
  street                     VARCHAR     NOT NULL DEFAULT 'UNKNOWN',
  house_number               VARCHAR     NOT NULL DEFAULT 'UNKNOWN',
  apartment_number           VARCHAR     NOT NULL DEFAULT 'UNKNOWN',
  postal_code                VARCHAR     NOT NULL DEFAULT 'UNKNOWN',
  city_id                    BIGINT      NOT NULL DEFAULT -1,
  city_name                  VARCHAR     NOT NULL DEFAULT 'UNKNOWN',
  region_id                  BIGINT      NOT NULL DEFAULT -1,
  region_name                VARCHAR     NOT NULL DEFAULT 'UNKNOWN',
  country_id                 BIGINT      NOT NULL DEFAULT -1,
  country_code               VARCHAR     NOT NULL DEFAULT 'UNKNOWN',
  country_name               VARCHAR     NOT NULL DEFAULT 'UNKNOWN',
  ta_insert_dt               DATE        NOT NULL DEFAULT CURRENT_DATE,
  ta_update_dt               DATE        NOT NULL DEFAULT CURRENT_DATE,
  source_system              VARCHAR     NOT NULL DEFAULT 'UNKNOWN',
  source_entity              VARCHAR     NOT NULL DEFAULT 'UNKNOWN',
  source_store_id            BIGINT      NOT NULL DEFAULT -1
);

CREATE TABLE IF NOT EXISTS bl_dm.dim_payments (
  payment_id                 BIGINT PRIMARY KEY DEFAULT -1,
  payment_method_id          BIGINT      NOT NULL DEFAULT -1,
  payment_method_name        VARCHAR     NOT NULL DEFAULT 'UNKNOWN',
  payment_status_id          BIGINT      NOT NULL DEFAULT -1,
  payment_status_name        VARCHAR     NOT NULL DEFAULT 'UNKNOWN',
  payment_currency_id        BIGINT      NOT NULL DEFAULT -1,
  payment_currency_name      VARCHAR     NOT NULL DEFAULT 'UNKNOWN',
  payment_processor_id       BIGINT      NOT NULL DEFAULT -1,
  payment_processor_name     VARCHAR     NOT NULL DEFAULT 'UNKNOWN',
  payment_dt                 DATE        NOT NULL DEFAULT DATE '1900-01-01',
  ta_insert_dt               DATE        NOT NULL DEFAULT CURRENT_DATE,
  ta_update_dt               DATE        NOT NULL DEFAULT CURRENT_DATE,
  source_system              VARCHAR     NOT NULL DEFAULT 'UNKNOWN',
  source_entity              VARCHAR     NOT NULL DEFAULT 'UNKNOWN',
  source_payment_id          VARCHAR     NOT NULL DEFAULT 'UNKNOWN'
);

CREATE TABLE IF NOT EXISTS bl_dm.dim_dates (
  date_id                    BIGINT PRIMARY KEY DEFAULT -1,
  full_date                  DATE        NOT NULL DEFAULT DATE '1900-01-01',
  day_of_week                VARCHAR     NOT NULL DEFAULT 'UNKNOWN',
  day_name                   VARCHAR     NOT NULL DEFAULT 'UNKNOWN',
  week_of_year               BIGINT      NOT NULL DEFAULT -1,
  month                      BIGINT      NOT NULL DEFAULT -1,
  month_name                 VARCHAR     NOT NULL DEFAULT 'UNKNOWN',
  quarter                    BIGINT      NOT NULL DEFAULT -1,
  year                       BIGINT      NOT NULL DEFAULT -1,
  is_weekend                 BOOLEAN     NOT NULL DEFAULT FALSE,
  is_holiday                 BOOLEAN     NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS bl_dm.dim_products_scd (
  product_id                 BIGINT PRIMARY KEY DEFAULT -1,
  product_name               VARCHAR     NOT NULL DEFAULT 'UNKNOWN',
  category_id                BIGINT      NOT NULL DEFAULT -1,
  category_name              VARCHAR     NOT NULL DEFAULT 'UNKNOWN',
  brand_id                   BIGINT      NOT NULL DEFAULT -1,
  brand_name                 VARCHAR     NOT NULL DEFAULT 'UNKNOWN',
  product_description        VARCHAR     NOT NULL DEFAULT 'UNKNOWN',
  product_price              DECIMAL     NOT NULL DEFAULT 0,
  product_country_of_origin_id BIGINT    NOT NULL DEFAULT -1,
  country_code               VARCHAR     NOT NULL DEFAULT 'UNKNOWN',
  country_name               VARCHAR     NOT NULL DEFAULT 'UNKNOWN',
  product_margin_rate        DECIMAL     NOT NULL DEFAULT 0,
  ta_start_dt                DATE        NOT NULL DEFAULT CURRENT_DATE,
  ta_end_dt                  DATE        NOT NULL DEFAULT DATE '9999-12-31',
  is_active                  BOOLEAN     NOT NULL DEFAULT FALSE,
  ta_insert_dt               DATE        NOT NULL DEFAULT CURRENT_DATE,
  source_system              BIGINT      NOT NULL DEFAULT -1,
  source_entity              BIGINT      NOT NULL DEFAULT -1,
  source_product_id          VARCHAR     NOT NULL DEFAULT 'UNKNOWN'
);


CREATE TABLE IF NOT EXISTS bl_dm.fact_order_items (
  order_id                              BIGINT  NOT NULL DEFAULT -1,
  product_id                            BIGINT  NOT NULL DEFAULT -1,
  customer_id                           BIGINT  NOT NULL DEFAULT -1,
  order_date_id                         BIGINT  NOT NULL DEFAULT -1,
  payment_id                            BIGINT  NOT NULL DEFAULT -1,
  order_status_id                       BIGINT  NOT NULL DEFAULT -1,
  quantity                              BIGINT  NOT NULL DEFAULT 0,
  discount_amount                       BIGINT  NOT NULL DEFAULT 0,
  order_items_amount                    BIGINT  NOT NULL DEFAULT 0,
  order_items_amount_after_discount     BIGINT  NOT NULL DEFAULT 0,
  delivery_id                           BIGINT  NOT NULL DEFAULT -1,
  store_id                              BIGINT  NOT NULL DEFAULT -1,
  cashier_id                            BIGINT  NOT NULL DEFAULT -1,
  warehouse_id                          BIGINT  NOT NULL DEFAULT -1,
  PRIMARY KEY (order_id, product_id),
  CONSTRAINT fk_foi_product     FOREIGN KEY (product_id)     REFERENCES bl_dm.dim_products_scd (product_id),
  CONSTRAINT fk_foi_customer    FOREIGN KEY (customer_id)    REFERENCES bl_dm.dim_customers (customer_id),
  CONSTRAINT fk_foi_date        FOREIGN KEY (order_date_id)  REFERENCES bl_dm.dim_dates (date_id),
  CONSTRAINT fk_foi_payment     FOREIGN KEY (payment_id)     REFERENCES bl_dm.dim_payments (payment_id),
  CONSTRAINT fk_foi_status      FOREIGN KEY (order_status_id)REFERENCES bl_dm.dim_order_status (order_status_id),
  CONSTRAINT fk_foi_delivery    FOREIGN KEY (delivery_id)    REFERENCES bl_dm.dim_deliveries (delivery_id),
  CONSTRAINT fk_foi_store       FOREIGN KEY (store_id)       REFERENCES bl_dm.dim_stores (store_id),
  CONSTRAINT fk_foi_cashier     FOREIGN KEY (cashier_id)     REFERENCES bl_dm.dim_cashiers (cashier_id),
  CONSTRAINT fk_foi_warehouse   FOREIGN KEY (warehouse_id)   REFERENCES bl_dm.dim_warehouses (warehouse_id)
);